name: ats_frontend
description: "A new Flutter project for Ambulance Tracking System."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- UPDATED: Using OpenStreetMap instead of Google Maps ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.0 # Helper package for flutter_map

  # For Socket.IO client
  socket_io_client: ^2.0.3+1

  # For storing tokens and small key-value pairs
  shared_preferences: ^2.2.0

  # For animated icons and effects
  lottie: ^3.1.0

  # For simple state management and dependency injection
  provider: ^6.1.2
  flutter_svg: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/hero_illustration.svg
    - assets/images/ambulance_marker.svg
  

